import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
// ignore: avoid_web_libraries_in_flutter
import 'dart:html' as html;

class GeminiConfig {
  static const String _storageKey = 'vernexa_gemini_api_key';
  String apiKey;

  GeminiConfig({this.apiKey = ''}) {
    _loadPersistedKey();
  }

  void _loadPersistedKey() {
    if (kIsWeb) {
      try {
        final saved = html.window.localStorage[_storageKey];
        if (saved != null && saved.trim().isNotEmpty) {
          apiKey = saved.trim();
        }
      } catch (_) {}
    }
  }

  void persistKey(String key) {
    apiKey = key.trim();
    if (kIsWeb) {
      try {
        if (apiKey.isEmpty) {
          html.window.localStorage.remove(_storageKey);
        } else {
          html.window.localStorage[_storageKey] = apiKey;
        }
      } catch (_) {}
    }
  }

  bool get isConfigured => apiKey.trim().isNotEmpty && apiKey.trim().startsWith('AIzaSy');
}

class GeminiTranslationResult {
  final String translatedText;
  final String phoneticGuide;

  GeminiTranslationResult({
    required this.translatedText,
    required this.phoneticGuide,
  });
}

class GeminiTranslationService {
  static final GeminiTranslationService instance = GeminiTranslationService._internal();
  GeminiTranslationService._internal();

  final GeminiConfig config = GeminiConfig();

  static const String _endpoint =
      'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent';

  static const String _systemInstruction = '''
You are VERNEXA AI: an expert educational linguist specializing in Indian tribal and regional languages (Mundari, Santali, Ho, Kurukh, Gondi, Hindi, English).
Your mission is to translate classroom phrases between teachers and primary school students.

AUTHENTIC TRIBAL LEXICON GUIDELINES:
1. SANTALI (ᱥᱟᱱᱛᱟᱲᱤ / संताली):
   - Greetings: 'ᱡᱚᱦᱟᱨ' (Johar)
   - Children: 'ᱜᱤᱫᱽᱨᱟᱹ' (Gidra)
   - Books: 'ᱯᱚᱛᱚᱵ' (Potob)
   - Numbers 1 to 10: 'ᱢᱤᱫ, ᱵᱟᱨ, ᱯᱮ, ᱯᱩᱱ, ᱢᱚᱬᱮ, ᱛᱩᱨᱩᱭ, ᱮᱭᱟᱭ, ᱤᱨᱟᱹᱞ, ᱟᱨᱮ, ᱜᱮᱞ' (Mid, Bar, Pe, Pun, Mone, Turui, Eayay, Iral, Aare, Gel)
   - Water: 'ᱫᱟᱜ' (Dag)

2. MUNDARI (मुण्डारी):
   - Greetings: 'जोहार' (Johar)
   - Children: 'गड़ाको' (Gadako) / 'होड़ोको' (Hodoko)
   - Book: 'पुथी' (Puthi)
   - Numbers: 'मियद, बारिया, आपिया, उपुन, मोणोय, तुरूय, एया, इरिल, आरे, गेले' (Miyad, Bariya, Aapiya, Upun, Monoy, Turui, Eya, Iril, Aare, Gele)
   - Water: 'दा:' (Da:)

3. HO (ᱦᱳ / हो):
   - Greetings: 'जोहार' (Johar)
   - Children: 'होनको' (Honko)
   - Numbers: 'मियद, बारिया, आपेया, उपुन, मोणोया, तुरूया, एया, इरिया, आरेया, गेले' (Miyad, Bariya, Apeya, Upun, Monoya, Turuya, Eya, Iriya, Areya, Gele)
   - Water: 'दा:' (Da:)

4. KURUKH (कुड़ुख़ / उरांव):
   - Greetings: 'जोहार' (Johar)
   - Children: 'तंगड़ाको' (Tangdako)
   - Water: 'अम्म' (Amm)

5. GONDI (गोंडी):
   - Greetings: 'जय जोहार / सेवा जोहार' (Jai Johar)
   - Children: 'पिलाक' (Pilak)
   - Water: 'येर' (Yer)

OUTPUT FORMAT:
Return strictly a valid JSON object with exactly two keys:
{
  "translatedText": "<Accurate translation in native script: Ol Chiki for Santali if possible or Devanagari>",
  "phoneticGuide": "<Romanized easy-to-pronounce phonetic guide with standard Latin letters for the teacher>"
}
''';

  void updateApiKey(String key) {
    config.persistKey(key);
  }

  Future<GeminiTranslationResult> translate({
    required String text,
    required String sourceLanguage,
    required String targetLanguage,
  }) async {
    if (!config.isConfigured) {
      throw Exception('Gemini API key is not configured.');
    }

    final url = Uri.parse('$_endpoint?key=${config.apiKey}');

    final prompt = '''
Translate the following classroom sentence from $sourceLanguage to $targetLanguage:
"$text"
''';

    final requestBody = jsonEncode({
      'contents': [
        {
          'role': 'user',
          'parts': [
            {'text': prompt}
          ]
        }
      ],
      'systemInstruction': {
        'parts': [
          {'text': _systemInstruction}
        ]
      },
      'generationConfig': {
        'temperature': 0.2,
        'responseMimeType': 'application/json',
      }
    });

    final response = await http.post(
      url,
      headers: {'Content-Type': 'application/json'},
      body: requestBody,
    );

    if (response.statusCode != 200) {
      throw Exception('Gemini API Error: (${response.statusCode}) ${response.body}');
    }

    final data = jsonDecode(response.body);
    final rawJsonText =
        data['candidates']?[0]?['content']?[0]?['parts']?[0]?['text'] ??
        data['candidates']?[0]?['content']?['parts']?[0]?['text'];

    if (rawJsonText == null) {
      throw Exception('No response generated by Gemini.');
    }

    final parsed = jsonDecode(rawJsonText as String);
    final translated = parsed['translatedText'] as String? ?? text;
    final phonetic = parsed['phoneticGuide'] as String? ?? '';

    return GeminiTranslationResult(
      translatedText: translated,
      phoneticGuide: phonetic,
    );
  }
}
